[build]
  command = "npm install"
  publish = "public"

[functions]
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm run dev"